#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "Gemfile", "README.md"]

# the base hostname & protocol for your site
# url: "http://localhost:4000"
# url: "https://www.cloudplatform.fi"
url: "https://cloudplatformfi.github.io"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Cloudplatform Jelastic
# Website language
lang: fi-FI
# Header Title
header-title: Sovellukset pilveen <strong>helposti</strong>
# Header Tagline
headter-tagline: Cloudplatform Jelastic
# Permalinks
# permalink: /:title:output_ext
# permalink: pretty
permalink: :slug/

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Ota Käyttöön
  url: https://app.fi.cloudplatform.fi/?lang=fi&signup=true

# Secondary Buttons
header-secondary-button:
  title: Lue Lisää
  url: /#features

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: jelastic@cloudplatform.fi

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://app.fi.cloudplatform.fi/?lang=fi&signup=true

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: Lupu Pitkänen
  author-tagline: PaaS-arkkitehti
  author-info: Lupulla on 20 vuoden kokemus websovellusten ylläpidosta ja alustoista.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDVQ7-TG4AAPGN_uRhbkolhnrokRaN4bPA
map-text: Cloudplatform / Planeetta
map-text-location: Helsinki, Finland
map-lat: 60.2043741
map-lng: 24.899685099999942

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome to Sera
about-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Alustat
portfolio-description: Jelasticin tukemat valmiit PaaS-sovellusalustat sekä esimerkkejä sovelluksista jotka on helppo ottaa siellä käyttöön
#
# Portfolio Grid
#
portfolio-categories: [Websites, Logo, Graphic Design, Development, Video, Photography]
portfolio:

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites, Graphic Design]
  image: img-01.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Graphic Design, Logo, Websites]
  image: img-02.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Graphic Design, Logo, Photography]
  image: img-03.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites, Video, Photography]
  image: img-04.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Development, Logo]
  image: img-05.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Development, Video]
  image: img-06.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites, Graphic Design]
  image: img-07.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites , Video]
  image: img-08.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Photography, Logo]
  image: img-09.jpg
  url: '#'


#####################################
##########  Core Features  ##########
#####################################
core-title: Jelastic ominaisuudet
core-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

#
# Core Features Left
#
core-features-left:

# Feature
- name: Creative
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-light

# Feature
- name: Minimalism
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-drop

# Feature
- name: Clean Coding
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-coffee

# Feature
- name: Friendly
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-smile

#
# Core Features Right
#
core-features-right:

# Feature
- name: Branding
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-wine

# Feature
- name: Web Design
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-monitor

# Feature
- name: Graphic Design
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-crop

# Feature
- name: Photography
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-camera


#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

#
# Testimonials
#
testimonials:

# Client
- name: Johnatan Doe
  url: http://themeforest.net
  url-text: ThemeForest.net
  avatar: avatar-01.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: themeforest.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
############### Team ################
#####################################
team-title: Cloudplatform tiimi
team-description: Tiimillämme on pitkä kokemus websovelluksista, sivustoista ja eri sovellusalustoista. Autamme mielellämme saamaan sovelluksenne sujuvasti pilveen!

#
# Team Members
#
team:

# Team Member
- name: Ville
  tagline: Sovellusasiantuntija
  avatar: ville.jpg

# Team Member
- name: Kim
  tagline: Sovellusasiantuntija
  avatar: kim.jpg

# Team Member
- name: Jouni
  tagline: Sovellusasiantuntija
  avatar: jouni.jpg

# Team Member
- name: Lupu
  tagline: Järjestelmäasiantuntija
  avatar: lupu.jpg



#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Hinnoittelu käytön mukaan
pricing-description: Cloudplatform Jelastic hinnoittelun tärkein yksikkö on Cloudlet, joka sisältää 128 Mt muistia (RAM) ja 400 MHz prosessoritehoa (CPU). Hinnoittelu skaalautuu automaattisesti - maksat vain siitä sovelluksen todellisen tehon kulutuksen mukaan. Voit määritellä ympäristöllesi Cloudletien enimmäismäärän, jolloin varmistat katon kustannuksille. Toisaalta saat reilun alennuksen jos sitoudut tiettyyn Cloudletien määrään.

#
# Plan Personal
#
plan-personal-price: "0,07"
plan-personal-offer-1-title: SSD-suorituskykyä
plan-personal-offer-1-info: Palvelinympäristöjen käytössä on erittäin suorituskykyinen tallennus SSD-levyille
plan-personal-offer-2-title: Tiedot turvassa
plan-personal-offer-2-info: Kaikki data sijaitsee kotimaassa, se on AES-256 salakirjoitettu levyllä ja varmuuskopiointi sisältyy hintaan
plan-personal-url: '/hinnat'

#
# Plan Business
#
plan-business-price: "6,21"
plan-business-offer-1-title: Suoritintehoa
plan-business-offer-1-info: Yksi cloudlet = 400 MHz suoritintehoa modernista Intel Xeon E5-2683 v4 CPU:sta
plan-business-offer-2-title: Muistia joustavasti
plan-business-offer-2-info: Yksi cloudlet = 128 Mt muistia, laskutetaan sovelluksen todellisen käytön mukaan tunti kerrallaan
plan-business-url: 'https://app.fi.cloudplatform.fi/?lang=fi&signup=true'

#
# Plan Ultimate
#
plan-ultimate-price: "3,56"
plan-ultimate-offer-1-title: Julkinen IPv4-osoite 
plan-ultimate-offer-1-info: Julkinen IPv4-osoite jonka takana on nelinkertaisesti varmistetut runkoverkkoyhteydet (Level3, Cogent, Telia ja FNE)
plan-ultimate-offer-2-title: Varmistetut yhteydet
plan-ultimate-offer-2-info: Yhteydet internetiin jonka takana on nelinkertaisesti varmistetut runkoverkkoyhteydet (Level3, Cogent, Telia ja FNE) 
plan-ultimate-url: '/hinnat'


#####################################
############   Contact   ############
#####################################
contact-title: Ota yhteyttä
contact-description: Tarvitsetko vielä lisätietoja tai haluatko keskustella mikä olisi paras ratkaisu tarpeeseenne? Jätä meille viesti tai soittopyyntö niin jutellaan!


#####################################
#############   Footer   ############
#####################################
footer-description: Cloudplatform on osa Planeettaa. Vuonna 2002 perustettu Planeetta on Suomen suurin itsenäinen webhostingia tarjoava yritys. Sillä on kymmeniä tuhansia asiakkaita ja verkkotunnuksia ylläpidossaan.
footer-copyright-text: Planeetta Internet Oy
footer-copyright-url: https://www.planeetta.fi/
footer-copyright-year: 2018
