#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "Gemfile", "README.md"]

# the base hostname & protocol for your site
# url: "http://localhost:4000"
# url: "https://www.cloudplatform.fi"
url: "https://www.cloudplatform.fi"

####################################
######   Optional Features    ######
####################################
smooth-scroll: true

####################################
###########   Plugins    ###########
####################################

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Cloudplatform pilvipalvelu
# Website language
lang: fi-FI
# Header Title
header-title: Sovellukset <strong>helposti</strong> pilveen
# Header Tagline
headter-tagline: Cloudplatform
# Permalinks
# permalink: /:title:output_ext
# permalink: pretty
permalink: :slug/

google_analytics: UA-120532186-1

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Ota Käyttöön
  url: https://app.fi.cloudplatform.fi/?lang=fi&signup=true

# Secondary Buttons
header-secondary-button:
  title: Lue Lisää
  url: /#edut

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: support@cloudplatform.fi

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://app.fi.cloudplatform.fi/?lang=fi&signup=true

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: lupu.jpg
  author-name: Lupu Pitkänen
  author-tagline: Pilviarkkitehti
  author-info: Lupulla on vaatimaton 20 vuoden kokemus websovellusalustoista.
  author-social-links:
    twitter: 'https://twitter.com/LupuPitkanen'
    linkedin: 'https://www.linkedin.com/in/lupu-pitk%C3%A4nen-6734872/'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDVQ7-TG4AAPGN_uRhbkolhnrokRaN4bPA
map-text: Cloudplatform / Planeetta
map-text-location: Helsinki, Finland
map-lat: 60.2043741
map-lng: 24.899685099999942

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Mikä Cloudplatform?
about-description: Cloudplatform on kotimainen Platform-as-a-Service -pilvipalvelu. Sen avulla siirrät sovelluksesi helposti pilveen ilman koodimuutoksia, käyttäen tuttuja työkaluja ja ilman turruttavaa API-dokumentaation kahlaamista. Cloudplatformin moottorina toimii palkittu <a href="https://jelastic.com/" target="_blank">Jelastic</a>-pilvialusta.


#####################################
#############  Features  ############
#####################################
features-title: Miksi Cloudplatform?
features-description: Koska se on ylivoimaisesti helpoin tapa saada sovellukset tuotantoon!

#
# Features
#
features:

# Feature
- title: Helppo deployment
  description: Node.js, PHP, Java, Ruby, Go tai Python sovelluksesi pilveen ilman koodimuutoksia haluamallasi työkalulla - Docker, GIT, SVN tai zip-paketti ja Maven, Ant, Eclipse, NetBeans tai IntelliJ IDEA -plugin.
  icon: pe-7s-next-2

# Feature
- title: Helppo skaalaus
  description: Vertikaalinen skaalautuminen reaaliaikaisesti ja horisontaalinen skaalautuminen automaattisesti - maksat kapasiteetista vain todellisen käytön mukaan.
  icon: pe-7s-rocket

# Feature
- title: Helppo hallinta
  description: Helppo web-käyttöliittymä - sovellusten deployment, palvelinympäristöjen orkestrointi, konfiguraatiot, lokitiedostot, palomuuraus, tilastot, SSH-yhteydet, jne.
  icon: pe-7s-airplay


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Alustat ja ohjelmointikielet
portfolio-description: Cloudplatform on käyttövalmis PaaS-pilvipalvelu suosituimmille ohjelmointikielille, sovellusalustoille ja tietokannoille. Koodaa ja julkaise!
#
# Portfolio Grid
#
portfolio-categories: [Ohjelmointikieli, Sovellusalusta, Tietokanta]
portfolio:

# Portfolio Item
- title: Java
  categories: [Ohjelmointikieli]
  image: java.png
  url: 'https://www.java.com/'

- title: PHP
  categories: [Ohjelmointikieli]
  image: php.png
  url: 'http://php.net/'

- title: Docker
  categories: [Sovellusalusta]
  image: docker.png
  url: 'https://www.docker.com/'

- title: Node.js
  categories: [Ohjelmointikieli, Sovellusalusta]
  image: nodejs.png
  url: 'https://nodejs.org/'

- title: Ruby
  categories: [Ohjelmointikieli]
  image: ruby.png
  url: 'https://www.ruby-lang.org/'

- title: Python
  categories: [Ohjelmointikieli]
  image: python.png
  url: 'https://www.python.org/'

- title: Go
  categories: [Ohjelmointikieli]
  image: golang.png
  url: 'https://golang.org/'

- title: Tomcat
  categories: [Sovellusalusta]
  image: tomcat.png
  url: 'http://tomcat.apache.org/'

- title: TomEE
  categories: [Sovellusalusta]
  image: tomee.png
  url: 'http://tomee.apache.org/'

- title: GlassFish
  categories: [Sovellusalusta]
  image: glassfish.png
  url: 'https://javaee.github.io/glassfish/'

- title: Jetty
  categories: [Sovellusalusta]
  image: jetty.png
  url: 'https://www.eclipse.org/jetty/'

- title: Apache
  categories: [Sovellusalusta]
  image: apache.png
  url: 'https://httpd.apache.org/'

- title: NGINX
  categories: [Sovellusalusta]
  image: nginx.png
  url: 'https://nginx.org/'

- title: JBoss
  categories: [Sovellusalusta]
  image: jboss.png
  url: 'http://www.jboss.org/'

- title: WildFly
  categories: [Sovellusalusta]
  image: wildfly.png
  url: 'http://wildfly.org/'

- title: WebLogic Server
  categories: [Sovellusalusta]
  image: weblogic.png
  url: 'http://www.oracle.com/technetwork/middleware/weblogic/overview/index.html'

- title: MariaDB
  categories: [Tietokanta]
  image: mariadb.png
  url: 'https://mariadb.org/'

- title: MySQL
  categories: [Tietokanta]
  image: mysql.png
  url: 'https://www.mysql.com/'

- title: MongoDB
  categories: [Tietokanta]
  image: mongodb.png
  url: 'https://www.mongodb.com/'

- title: PostgreSQL
  categories: [Tietokanta]
  image: postgresql.png
  url: 'https://www.postgresql.org/'

- title: CouchDB
  categories: [Tietokanta]
  image: couchdb.png
  url: 'http://couchdb.apache.org/'

- title: Cassandra
  categories: [Tietokanta]
  image: cassandra.png
  url: 'http://cassandra.apache.org/'

- title: OrientDB
  categories: [Tietokanta]
  image: orientdb.png
  url: 'https://orientdb.com/'

- title: Redis
  categories: [Tietokanta]
  image: redis.png
  url: 'https://redis.io/'

- title: Neo4j
  categories: [Tietokanta]
  image: neo4j.png
  url: 'https://neo4j.com/'

- title: Oracle DB
  categories: [Tietokanta]
  image: oracle.png
  url: 'https://www.oracle.com/database/index.html'

- title: PerconaDB
  categories: [Tietokanta]
  image: percona.png
  url: 'https://www.percona.com/'


#####################################
##########  Core Features  ##########
#####################################
core-title: Ominaisuudet
core-description: Palveluumme on lisätty vuosien varrella lukemattomia kehittäjien tarvitsemia ja toivomia ominaisuuksia. Tässä muutamia niistä. Tietoturvaa, käytettävyyttä, skaalautuvuutta ja kehittämisen helppoutta - kehitämme palvelua jatkuvasti!

#
# Core Features Left
#
core-features-left:

# Feature
- name: Skaalautuminen
  description: Automaattinen vertikaalinen ja horisontaalinen skaalaus
  icon: pe-7s-plane

# Feature
- name: Suoritusteho
  description: Moderni ja tehokas palvelinalusta (Intel Xeon E5-2683 v4 CPU)
  icon: pe-7s-bicycle

# Feature
- name: Legacy + mikropalvelut
  description: Legacy-projektit ja uudet mikropalvelut samalle alustalle 
  icon: pe-7s-cloud-upload

# Feature
- name: SSL ja HTTPS
  description: Ilmaiset tai omat SSL-sertifikaatit helposti käyttöön
  icon: pe-7s-medal

# Feature
- name: Kuormantasaus
  description: HTTP(S) ja TCP-kuormantasaus heti käyttövalmiina
  icon: pe-7s-shuffle

# Feature
- name: Myös IaaS-kapasiteetti
  description: Virtuaalipalvelimet root-oikeuksilla (CentOS tai Ubuntu)
  icon: pe-7s-server

# Feature
- name: Data kotimaassa
  description: Kaikki data sijaitsee Digitan konesalissa Helsingin Pasilassa
  icon: pe-7s-check

# Feature
- name: Puhumme suomea
  description: Kotimainen pilvipalvelu ja suomenkielinen asiakaspalvelu
  icon: pe-7s-chat

# Feature
- name: Maksa verkossa
  description: Verkkopankkitunnuksilla tai maksukortilla lisää saldoa
  icon: pe-7s-calculator

# Feature
- name: Laskutus
  description: Suomalainen lasku käytön mukaan kerran kuussa (<a href="#yhteys">pyydä erikseen</a>)
  icon: pe-7s-note2

# Feature
- name: GDPR-valmis
  description: EU:n tietosuoja-asetuksen mukainen alusta sovelluksille
  icon: pe-7s-ribbon

#
# Core Features Right
#
core-features-right:

# Feature
- name: PaaS ja Docker
  description: Valmiit PaaS-alustat tai omat Docker-imaget
  icon: pe-7s-cloud

# Feature
- name: Vikasietoisuus
  description: Automaatinen palautuminen palvelinlaitteen vikaantuessa
  icon: pe-7s-tools

# Feature
- name: SSD-levy
  description: Erittäin suorituskykyinen IO-teho SSD-levyillä
  icon: pe-7s-diskette

# Feature
- name: Klusterointi
  description: Sovellusten klusterointi helposti hallintapaneelista
  icon: pe-7s-network

# Feature
- name: Tiedostot
  description: Lokitiedot ja asetustiedostot helposta hallintapaneelista
  icon: pe-7s-config

# Feature
- name: AES-256 salaus
  description: Kaikki data on salakirjoitettu levyllä (AES-256)
  icon: pe-7s-lock

# Feature
- name: SSH-yhteydet
  description: SSH-avaimella gatewayn kautta tai web-hallintapaneelista
  icon: pe-7s-notebook

# Feature
- name: Oikeudet
  description: Jaa ja määrittele oikeuksia ympäristöihin eri käyttäjille
  icon: pe-7s-coffee

# Feature
- name: Elinkaari
  description: Sammuta, poista ja käynnistä palveluita uudelleen
  icon: pe-7s-power

# Feature
- name: DevOps
  description: Nopeasti alkuun omien DevOps-prosessien kehittämisessä
  icon: pe-7s-loop

# Feature
- name: Valvonta
  description: Hälytykset kuormituksesta (RAM, CPU, verkko, IO)
  icon: pe-7s-mail

#####################################
########### Testimonials ############
#####################################
testimonials-title: Asiakkaitamme
testimonials-description: Vuonna 2012 lanseerattu Cloudplatform on palvellut jo tuhansia suomalaisia yrityksiä ja projekteja laidasta laitaan. Asiakkainamme on niin pieniä digitoimistoja kuin skaalautuvia alustoja tarvitsevia ohjelmistoyrityksiä. Helppous kehittäjille on kuitenkin palvelumme suosion tärkein syy. Tervetuloa mukaan!

#
# Testimonials
#
testimonials:

# Client
- name: Jari Järvinen
  url: https://www.foredata.fi/
  url-text: www.foredata.fi
  avatar: foredata_jari.jpg
  cite: Cloudplatformista saamme joustavasti palvelinkapasiteettia käyttöön tarpeen mukaan. Arvostamme kotimaisen palvelun lisäksi erityisesti reaaliaikaista skaalautumista, missä maksamme kapasiteetista vain todellisen käytön mukaan.
  logo-img: foredata.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Blogi
blog-description: Cloudplatformin blogi on avattu! Kirjoitamme ajankohtaisista aiheista pilvialustoihin liittyen sekä käymme läpi palvelumme eri ominaisuuksia ja hyödyllisiä vinkkejä.


#####################################
############### Team ################
#####################################
team-title: Cloudplatform tiimi
team-description: Tiimillämme on pitkä kokemus websovelluksista, sivustoista ja eri sovellusalustoista. Autamme mielellämme saamaan sovelluksenne sujuvasti pilveen!

#
# Team Members
#
team:

# Team Member
- name: Ville
  tagline: Sovellusasiantuntija
  avatar: ville.jpg

# Team Member
- name: Kim
  tagline: Sovellusasiantuntija
  avatar: kim.jpg

# Team Member
- name: Jouni
  tagline: Sovellusasiantuntija
  avatar: jouni.jpg

# Team Member
- name: Lupu
  tagline: Pilviarkkitehti
  avatar: lupu.jpg


#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Hinnoittelu käytön mukaan
pricing-description: Cloudplatformin hinnoittelun tärkein yksikkö on Cloudlet, joka sisältää 128 Mt muistia (RAM) ja 400 MHz prosessoritehoa (CPU). Hinnoittelu skaalautuu automaattisesti - maksat vain siitä sovelluksen todellisen tehon kulutuksen mukaan. Voit määritellä ympäristöllesi Cloudletien enimmäismäärän, jolloin varmistat katon kustannuksille. Toisaalta saat reilun alennuksen jos sitoudut tiettyyn Cloudletien määrään.

#
# Plan Personal
#
plan-personal-price: "0,07"
plan-personal-offer-1-title: SSD-suorituskykyä
plan-personal-offer-1-info: Palvelinympäristöjen käytössä on erittäin suorituskykyinen tallennus SSD-levyille
plan-personal-offer-2-title: Tiedot turvassa
plan-personal-offer-2-info: Kaikki data sijaitsee kotimaassa, se on AES-256 salakirjoitettu levyllä ja varmuuskopiointi sisältyy hintaan
plan-personal-url: '/hinnat'

#
# Plan Business
#
plan-business-price: "6,21"
plan-business-offer-1-title: Suoritintehoa
plan-business-offer-1-info: Yksi cloudlet = 400 MHz suoritintehoa modernista Intel Xeon E5-2683 v4 CPU:sta
plan-business-offer-2-title: Muistia joustavasti
plan-business-offer-2-info: Yksi cloudlet = 128 Mt muistia, laskutetaan sovelluksen todellisen käytön mukaan tunti kerrallaan
plan-business-url: 'https://app.fi.cloudplatform.fi/?lang=fi&signup=true'

#
# Plan Ultimate
#
plan-ultimate-price: "3,56"
plan-ultimate-offer-1-title: Julkinen IP-osoite 
plan-ultimate-offer-1-info: Julkiset kiinteät ja muuttumattomat IPv4-osoitteet verkkopalvelullesi edullisesti.
plan-ultimate-offer-2-title: Varmistetut yhteydet
plan-ultimate-offer-2-info: Yhteydet internetiin moninkertaisesti varmistettuna usealta eri operaattorilta (Level3, Cogent, Telia ja FNE) 
plan-ultimate-url: '/hinnat'


#####################################
############   Contact   ############
#####################################
contact-title: Ota yhteyttä
contact-description: Tarvitsetko vielä lisätietoja tai haluatko keskustella mikä olisi paras ratkaisu tarpeeseenne? Jätä meille viesti tai soittopyyntö niin jutellaan!


#####################################
#############   Footer   ############
#####################################
footer-description: Cloudplatform on osa Planeettaa. Vuonna 2002 perustettu Planeetta on Suomen suurin itsenäinen webhostingia tarjoava yritys. Sillä on kymmeniä tuhansia asiakkaita ja verkkotunnuksia ylläpidossaan.
footer-copyright-text: Planeetta Internet Oy
footer-copyright-url: https://www.planeetta.fi/
footer-copyright-year: 2018
